DROP DATABASE `IROSE`;
CREATE DATABASE `IROSE` CHARACTER SET utf8 COLLATE utf8_bin;

CREATE TABLE `ACCOUNT` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	`NICKNAME` VARCHAR(45) NOT NULL,
	`PASSWORD` VARCHAR(128) NOT NULL,
	`EMAIL` VARCHAR(320) NOT NULL,
	`LOGGED` BOOLEAN NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE KEY (`NICKNAME`)
);

CREATE TABLE `MAP` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `LOCATION` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	`ID_MAP` BIGINT NOT NULL,
	`POINT_X` DOUBLE NOT NULL,
	`POINT_Y` DOUBLE NOT NULL,
	`POINT_Z` DOUBLE NOT NULL,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`ID_MAP`) REFERENCES `MAP`(`ID`)
);

CREATE TABLE `CHARACTER_STATS` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	`HP_LIMIT` INT NOT NULL,
	`MP_LIMIT` INT NOT NULL,
	`WEIGHT_LIMIT` INT NOT NULL,
	`SP_LIMIT` INT NOT NULL,
	`ATTACK` INT NOT NULL,
	`DEFENSE` INT NOT NULL,
	`ACCURACY` INT NOT NULL,
	`MAGIC_DEFENSE` INT NOT NULL,
	`DODGE` INT NOT NULL,
	`MOVEMENT_SPEED` INT NOT NULL,
	`ATTACK_SPEED` INT NOT NULL,
	`CRITICAL` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `CHARACTER` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	`ID_LOCATION` BIGINT NOT NULL,
	`ID_CHARACTER_STATS` BIGINT NOT NULL
	`NAME` VARCHAR(120) NOT NULL,
	`HP` INT NOT NULL,
	`MP` INT NOT NULL,
	`WEIGHT` INT NOT NULL,
	`SP` INT NOT NULL,
	`HP_RECOVERY` FLOAT NOT NULL,
	`MP_RECOVERY` FLOAT NOT NULL,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`ID_LOCATION`) REFERENCES `LOCATION`(`ID`),
	FOREIGN KEY (`ID_CHARACTER_STATS`) REFERENCES `CHARACTER_STATS`(`ID`)
);

CREATE TABLE `PLAYER_ATTRIBUTES` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	`STRENGTH` INT NOT NULL,
	`DEXTERITY` INT NOT NULL,
	`INTELLIGENCE` INT NOT NULL,
	`CONCENTRATION` INT NOT NULL,
	`CHARM` INT NOT NULL,
	`SENSE` INT NOT NULL,
	PRIMARY KEY (`ID`)
);
