INSERT INTO `ACCOUNT` (`ID`, `NICKNAME`, `PASSWORD`, `EMAIL`, `LOGGED`) VALUES (1, 'davi', SHA2('123', 512), 'daviarimateia93@gmail.com', true);
INSERT INTO `MAP` (`ID`) VALUES (1);
INSERT INTO `LOCATION` (`ID`, `ID_MAP`, `LOCATION_X`, `LOCATION_Y`, `LOCATION_Z`) VALUES (1, 1, 100, 0, 100);
INSERT INTO `CHARACTER_STATS` (`ID`, `HP_LIMIT`, `MP_LIMIT`, `WEIGHT_LIMIT`, `SP_LIMIT`, `ATTACK`, `DEFENSE`, `ACCURACY`, `MAGIC_DEFENSE`, `DODGE`, `MOVEMENT_SPEED`, `ATTACK_SPEED`, `CRITICAL`) VALUES (1, 300, 200, 500, 100, 300, 200, 150, 200, 100, 100, 100, 50);
INSERT INTO `CHARACTER` (`ID`, `ID_LOCATION`, `ID_CHARACTER_STATS`, `NAME`, `HP`, `MP`, `WEIGHT`, `SP`, `HP_RECOVERY`, `MP_RECOVERY`) VALUES (1, 1, 1, 'Jaspercabuloso', 300, 200, 200, 100, 1.0, 1.0);
INSERT INTO `PLAYER_ATTRIBUTES` (`ID`, `STRENGTH`, `DEXTERITY`, `INTELLIGENCE`, `CONCENTRATION`, `CHARM`, `SENSE`) VALUES (1, 10, 10, 10, 10, 10, 10);
