USE `IROSE`;

INSERT INTO `ACCOUNT` (`ID`, `NICKNAME`, `PASSWORD`, `EMAIL`, `LOGGED`) VALUES (1, 'davi', SHA2('123', 512), 'daviarimateia93@gmail.com', true);
INSERT INTO `MAP` (`ID`) VALUES (1);
INSERT INTO `LOCATION` (`ID`, `ID_MAP`, `POINT_X`, `POINT_Y`, `POINT_Z`) VALUES (1, 1, 100, 0, 100);
INSERT INTO `CHARACTER_AREA` (`ID`, `ID_LOCATION`, `RADIUS`) VALUES (1, 1, 250);
INSERT INTO `CHARACTER` (`ID`, `ID_CHARACTER_AREA`, `NAME`, `HP`, `MP`, `WEIGHT`, `SP`, `HP_RECOVERY`, `MP_RECOVERY`) VALUES (1, 1, 'Jaspercabuloso', 300, 200, 200, 100, 1.0, 1.0);
INSERT INTO `PLAYER_ATTRIBUTES` (`ID`, `STRENGTH`, `DEXTERITY`, `INTELLIGENCE`, `CONCENTRATION`, `CHARM`, `SENSE`) VALUES (1, 10, 10, 10, 10, 10, 10);
INSERT INTO `PLAYER` (`ID`, `ID_ACCOUNT`, `ID_PLAYER_ATTRIBUTES`, `ATTRIBUTES_POINTS`, `SKILL_POINTS`, `EXTRA_XP_RATE`, `EXTRA_DROP_RATE`) VALUES (1, 1, 1, 0, 0, 0, 0);
